apiVersion: v1
kind: Secret
metadata:
  name: mob-litellm-secrets
  namespace: mob
type: Opaque
stringData:
  LITELLM_MASTER_KEY: "sk-mob-litellm-change-me"
  ANTHROPIC_API_KEY: ""
  OPENAI_API_KEY: ""
