apiVersion: v1
kind: ServiceAccount
metadata:
  name: mob-api
  namespace: mob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mob-api
  namespace: mob
rules:
  - apiGroups: ["mob.io"]
    resources: ["sessions"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["mob.io"]
    resources: ["sessions/status"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mob-api
  namespace: mob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mob-api
subjects:
  - kind: ServiceAccount
    name: mob-api
    namespace: mob
