apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - crds/agentrun.yaml
  - operator/serviceaccount.yaml
  - operator/rbac.yaml
  - operator/deployment.yaml
  - agent-rbac.yaml

commonLabels:
  app.kubernetes.io/name: mob
  app.kubernetes.io/managed-by: kustomize
