apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mob-api
  namespace: mob
  labels:
    app.kubernetes.io/name: mob
    app.kubernetes.io/component: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mob.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mob-api
                port:
                  number: 8080
