apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mob-operator
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups: ["mob.io"]
    resources: ["sessions"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["mob.io"]
    resources: ["sessions/status"]
    verbs: ["get", "patch"]
  - apiGroups: ["mob.io"]
    resources: ["sessions/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mob-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mob-operator
subjects:
  - kind: ServiceAccount
    name: mob-operator
    namespace: mob
