apiVersion: apps/v1
kind: Deployment
metadata:
  name: mob-api
  namespace: mob
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: mob-api
          image: mob-api:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
